name: Push

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run the script
        run: chmod +x ${GITHUB_WORKSPACE}/script.sh && sh ${GITHUB_WORKSPACE}/script.sh

      - name: DNSControl push
        uses: koenrh/dnscontrol-action@v3.18.1
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        with:
          args: push

          # Optionally, if your DNSConfig files are in a non-default location,
          # you could specify the paths to the config and credentials file.
          config_file: 'dns/dnsconfig.js'
          creds_file: 'dns/creds.json'
